//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SramComparer.SoE.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SramComparer.SoE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die changes at every in-game save ähnelt.
        /// </summary>
        public static string ChangesAtEveryInSaveSlotSave {
            get {
                return ResourceManager.GetString("ChangesAtEveryInSaveSlotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checksum ähnelt.
        /// </summary>
        public static string Checksum {
            get {
                return ResourceManager.GetString("Checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checksum of all save slots ähnelt.
        /// </summary>
        public static string ChecksumsAllSlots {
            get {
                return ResourceManager.GetString("ChecksumsAllSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checksum when different ähnelt.
        /// </summary>
        public static string ChecksumWhenDifferent {
            get {
                return ResourceManager.GetString("ChecksumWhenDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show checksum of compared save slot ähnelt.
        /// </summary>
        public static string CommandShowChecksumOfComparedSaveSlot {
            get {
                return ResourceManager.GetString("CommandShowChecksumOfComparedSaveSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show checksums of all save slots ähnelt.
        /// </summary>
        public static string CommandShowChecksumsOfAllSaveSlots {
            get {
                return ResourceManager.GetString("CommandShowChecksumsOfAllSaveSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Unknown12B value of compared save slot ähnelt.
        /// </summary>
        public static string CommandShowUnknown12BValueOfComparedSaveSlot {
            get {
                return ResourceManager.GetString("CommandShowUnknown12BValueOfComparedSaveSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Unknown12B values of all save slots ähnelt.
        /// </summary>
        public static string CommandShowUnknown12BValuesOfAllSaveSlots {
            get {
                return ResourceManager.GetString("CommandShowUnknown12BValuesOfAllSaveSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die compared with save slot {0} ähnelt.
        /// </summary>
        public static string ComparedWithOtherSaveSlotTemplate {
            get {
                return ResourceManager.GetString("ComparedWithOtherSaveSlotTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die invalid ähnelt.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown12B of all save slots ähnelt.
        /// </summary>
        public static string Unknown12BAllSlots {
            get {
                return ResourceManager.GetString("Unknown12BAllSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown12B when different ähnelt.
        /// </summary>
        public static string Unknown12BWhenDifferent {
            get {
                return ResourceManager.GetString("Unknown12BWhenDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die valid ähnelt.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation-status ähnelt.
        /// </summary>
        public static string ValidationStatus {
            get {
                return ResourceManager.GetString("ValidationStatus", resourceCulture);
            }
        }
    }
}
