//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRAM.Comparison.SoE.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SRAM.Comparison.SoE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm room code ähnelt.
        /// </summary>
        public static string AlarmCode {
            get {
                return ResourceManager.GetString("AlarmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show checksums ähnelt.
        /// </summary>
        public static string CmdShowChecksum {
            get {
                return ResourceManager.GetString("CmdShowChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show checksums only if different ähnelt.
        /// </summary>
        public static string CmdShowChecksumIfDifferent {
            get {
                return ResourceManager.GetString("CmdShowChecksumIfDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show &apos;ScriptedEventTimer&apos; value ähnelt.
        /// </summary>
        public static string CmdShowScriptedEventTimer {
            get {
                return ResourceManager.GetString("CmdShowScriptedEventTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show &apos;ScriptedEventTimer&apos; value only if different ähnelt.
        /// </summary>
        public static string CmdShowScriptedEventTimerIfDifferent {
            get {
                return ResourceManager.GetString("CmdShowScriptedEventTimerIfDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show terminal codes ähnelt.
        /// </summary>
        public static string CmdShowTerminalCodes {
            get {
                return ResourceManager.GetString("CmdShowTerminalCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die changes at every in-game save ähnelt.
        /// </summary>
        public static string CompChangesAtEveryInSaveSlotSave {
            get {
                return ResourceManager.GetString("CompChangesAtEveryInSaveSlotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die compared with save slot {0} ähnelt.
        /// </summary>
        public static string CompComparedWithOtherSaveSlotTemplate {
            get {
                return ResourceManager.GetString("CompComparedWithOtherSaveSlotTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checksum ähnelt.
        /// </summary>
        public static string EnumChecksum {
            get {
                return ResourceManager.GetString("EnumChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checksum if different ähnelt.
        /// </summary>
        public static string EnumChecksumIfDifferent {
            get {
                return ResourceManager.GetString("EnumChecksumIfDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ScriptedEventTimer when different ähnelt.
        /// </summary>
        public static string EnumScriptedEventTimerIfDifferent {
            get {
                return ResourceManager.GetString("EnumScriptedEventTimerIfDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm code and secret boss room code aren&apos;t the same. ähnelt.
        /// </summary>
        public static string ErrorBothTerminalCodesAreNotEqual {
            get {
                return ResourceManager.GetString("ErrorBothTerminalCodesAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die invalid ähnelt.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change secret boss room code? 1 = yes / 0 = no ähnelt.
        /// </summary>
        public static string PromptChangeSecretBossRoomCode {
            get {
                return ResourceManager.GetString("PromptChangeSecretBossRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Secret boss room code ähnelt.
        /// </summary>
        public static string SecretBossRoomCode {
            get {
                return ResourceManager.GetString("SecretBossRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Because both codes are equal, secret boss room door won&apos;t open. Consider changing the secret boss room code. ähnelt.
        /// </summary>
        public static string StatusBothTerminalCodesAreEqual {
            get {
                return ResourceManager.GetString("StatusBothTerminalCodesAreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New secret boss room code ähnelt.
        /// </summary>
        public static string StatusNewSecretBossRoomCode {
            get {
                return ResourceManager.GetString("StatusNewSecretBossRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This saveslot seems to be empty ähnelt.
        /// </summary>
        public static string StatusSaveslotIsEmpty {
            get {
                return ResourceManager.GetString("StatusSaveslotIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminal codes ähnelt.
        /// </summary>
        public static string TerminalCodes {
            get {
                return ResourceManager.GetString("TerminalCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die valid ähnelt.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
    }
}
